runtime: nodejs10

instance_class: F2

default_expiration: 4d 5h

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|webp))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|webp)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'